# Generated by Django 6.0.1 on 2026-01-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_message",
            field=models.TextField(
                default="The Junior's Restaurant customer support team is here to Serve you. Please place your order at our Restaurant on 0701126433 OR with the Bakeshop on 0701126433"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="whatsapp_number",
            field=models.CharField(default="256701126433", max_length=20),
        ),
    ]
